# Generated by Django 3.1.4 on 2020-12-31 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('A', models.TextField()),
                ('B', models.TextField()),
                ('C', models.TextField()),
                ('D', models.TextField()),
                ('E', models.TextField()),
                ('F', models.TextField()),
                ('G', models.TextField()),
                ('H', models.TextField()),
                ('I', models.TextField()),
                ('J', models.TextField()),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
    ]
