# Generated by Django 3.1.4 on 2021-01-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_url', models.CharField(blank=True, max_length=254, null=True)),
                ('twitter_url', models.CharField(blank=True, max_length=254, null=True)),
                ('reddit_url', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
