# Generated by Django 3.1.4 on 2021-03-23 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Social',
        ),
    ]
